# Generated by Django 3.2.5 on 2021-07-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cricket_Tournament_API', '0002_auto_20210723_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries_table',
            name='Current_Tropy_Holder',
        ),
    ]
